---
- name: Install and Start Apache
  hosts: all
  become: yes
  vars:
    apache_package: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
    apache_service: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
  tasks:
    - name: Install Apache
      apt:
        name: "{{ apache_package }}"
        state: present
      when: ansible_os_family == "Debian"
      yum:
        name: "{{ apache_package }}"
        state: present
      when: ansible_os_family == "RedHat" 